### ISSUE TITLE
Add .edgerc support

### ISSUE THREAD

**Issue by ktyacke** [njuettner/edgegrid#1]
Please add support for ingesting credentials from a .edgerc file. An example of this can be found in the Python signing library at https://github.com/akamai-open/AkamaiOPEN-edgegrid-python . An .edgerc file is simply a .ini file that is commonly used to store credentials used in requests to the OPEN API. Any .ini parser should be able to read it as it is in standard .ini format. This file is most often stored in the users home directory (i.e. "~/.edgerc"), but your program should accept a path to this file as one of it's params.

**Comment by njuettner** [comment]
INI are supported now :).
